### ISSUE TITLE
Correctly selecting best possible branch?

### ISSUE THREAD

**Issue by DarioBernardo** [pbsinclair42/MCTS#8]
Hi,
thank you for your work, really good stuff.
I am a bit confused however on one point of the implementation logic. 
Let's assume I need to decide the best possible action between A and B, given an initial state and a number of iteration limit parameter (let's say `limit = 1000`).

In the first two iterations, until the node [is fully expanded ](https://github.com/pbsinclair42/MCTS/blob/366972d8dc96254f51aa7b1311e03341cf518f87/mcts.py#L70) all the branches (or node's childs)  are explored. Therefore, going back to our example, after two iterations both branch A and B are explored once. Great.
However when the node is expanded and both branches are visited once, there are a number of things that can happen:
 * When exploring branch A, A wins. When exploring branch B, B loses
 *  When exploring A, A loses. When exploring B, B wins
 * Both A and B wins or loses.

In case A wins (same applies with reversed letters in case B wins), then when I execute round number 3, on [selectNode()](https://github.com/pbsinclair42/MCTS/blob/366972d8dc96254f51aa7b1311e03341cf518f87/mcts.py#L64) the best child is selected, in this case A. 

The problem I have noticed is that at the end of the  1000 iterations, branch A is explored 999 times (node.numVisit), while branch B is explored just once, at the beginning. 
It looks like that `getBestChild()` get stuck on the first branch which won and never recover from there, and in at the end of the simulation that would be the winning branch.

Something to consider is that I am using continuous rewards and not True, False (win or lose) rewards. 
I tried to play with the exploration constant, but didn't help.

Is the implementation correct? is there something to mitigate this you would suggest?
Thank you

**Comment by esparano** [comment]
I haven't experienced this, but there is another open issue with a possible implementation bug. It could be related.

A few other issues could be at fault. Are your custom rewards small, say in the range [-1, 1]? If not, the ratio between exploration-const and typical reward magnitude needs to be kept roughly the same.

**Comment by DarioBernardo** [comment]
Hi, and thanks for your response.
 My reward is a score, like in a video game, and starts from 0 with no upper bound, but generally a typical value would be between 0 and let's say 1000000. Does it mean that the exploration value must me in the same range? I actually tried that and you are right, it actually mitigated the problem. I have more visits in the less promising branch now, and at least it is not just 1. Also the game is more stable.
Could you also point me to the open issue with a possible implementation bug you are referring to in your response, so I can have a look? 
thank you

**Comment by esparano** [comment]
Hi Dario,

The open issue I referenced is https://github.com/pbsinclair42/MCTS/issues/6. I don't think it's related to your exploration issue, but it can potentially affect multi-player games.

If your values can be as high as 1M, then it makes sense why only one branch is being explored. Check out the code that chooses which branch to explore: https://github.com/pbsinclair42/MCTS/blob/366972d8dc96254f51aa7b1311e03341cf518f87/mcts.py#L98
Because totalReward is so high, the exploration component of the equation is mostly ignored.

There are two possible solutions I can recommend:
1) Increase explorationValue until it's in roughly the same range as a typical reward (then tweak it by up to an order of magnitude until you're getting good results).
2) Rework your reward function to return a value in a more reasonable range. Perhaps you simply divide your reward by 100k before returning it. Or perhaps you could apply a more complicated function like log or arctan to the reward. Some implementations even pass the game state through a neural network before returning a confidence value between [-1, 1]! There are a lot of options here.
